//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.1.0
//     from Assets/ChessAssets/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""CameraControls"",
            ""id"": ""e500076f-0792-4d5f-8be9-a116e20e8dac"",
            ""actions"": [
                {
                    ""name"": ""Zoom In"",
                    ""type"": ""Button"",
                    ""id"": ""b0db547f-818c-42e5-9861-2a470aad9a46"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""GameLeftClick"",
                    ""type"": ""Button"",
                    ""id"": ""30e41343-24c4-432c-b1c2-78fb934b257b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Zoom Out"",
                    ""type"": ""Button"",
                    ""id"": ""e67c7b64-c28b-4e03-a851-44e3ee86a13a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Rotate Left"",
                    ""type"": ""Value"",
                    ""id"": ""27899e4b-63ff-48f5-9479-0ca5278e183c"",
                    ""expectedControlType"": ""Key"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Rotate Right"",
                    ""type"": ""Value"",
                    ""id"": ""a8ac0f98-b884-444c-b07a-02355e38c3d5"",
                    ""expectedControlType"": ""Key"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""d2a8d2f8-9f83-49b8-b827-cb8832e9a80d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""be7b48ab-faa5-43c2-8658-59c5eabfabb3"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Zoom In"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c24b7d6-4a62-4d37-abd1-62edb3aeb83e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Zoom Out"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e3e874b1-5896-45eb-8d24-9cfd750bd80f"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Zoom Out"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b8a2dd71-84d0-480f-ad26-ff74cd7d5eee"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Rotate Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""68d6da66-7cc7-4a6e-834c-2f7521e2ada4"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Rotate Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2cb0a3f1-2d99-48e4-987b-59fa56cfa2e2"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Rotate Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fe021012-b5af-40b4-a81b-9d030a4b6b6c"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Rotate Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dacfa1e9-e385-4a38-8bb2-3c8fe57b7c9a"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""GameLeftClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cfa6d046-960c-43dc-87a3-87b32c0f93b7"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9b8ffff9-1e34-49c9-85e1-5164ed1cce95"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc868bc6-305a-45d7-8f1d-8f8ef1fca52d"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Zoom In"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PauseMenuControls"",
            ""id"": ""cc64a4ab-7341-4c08-938d-c0b1e781daff"",
            ""actions"": [
                {
                    ""name"": ""PauseOrientation"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ab05aeb9-43e4-42e3-970b-dcab34ed2400"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""PausePoint"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b30d9c09-ff2f-4528-adb8-9d033ae04477"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""PausePosition"",
                    ""type"": ""PassThrough"",
                    ""id"": ""2785def4-15ce-4c31-abf5-9268fa5b0f82"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""PauseCancel"",
                    ""type"": ""PassThrough"",
                    ""id"": ""92b29fb1-bae9-4c21-9356-7e646bea4f5d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""PauseSubmit"",
                    ""type"": ""PassThrough"",
                    ""id"": ""e695f360-8d91-43bd-9872-22009d13b4cb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""PauseNavigate"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ec4c81d6-c8a6-43dd-9da9-551c65873020"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""PauseScrollWheel"",
                    ""type"": ""Value"",
                    ""id"": ""43ac9e84-ab15-4d7e-9874-02f8d5755be1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""PauseRightClick"",
                    ""type"": ""Value"",
                    ""id"": ""d051ea8b-3cb0-4678-8419-5fd673e2f58c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""PauseLeftClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""a482560e-b8b7-434b-bc98-b657c5b79f9f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""PauseMiddleClick"",
                    ""type"": ""Value"",
                    ""id"": ""41214b39-4ac1-4425-8a10-261172e81a8f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""PauseQuitGame"",
                    ""type"": ""Button"",
                    ""id"": ""03319905-8484-443f-88e5-81de56da7b2b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press""
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""bd06ff35-2adc-4064-9541-f00e39ec8cef"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""PauseMiddleClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3fb105e-9b38-4fd5-9f63-8a9921c2c9fd"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""PauseLeftClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25cf1115-3bfb-4855-b1b2-35ada27f1c2f"",
                    ""path"": ""<Touchscreen>/touch*/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""PauseLeftClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""93e2e0f6-b9bb-4f91-b4d9-eca01ab3d2e3"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""PauseRightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c6758a8-371a-4c60-9f19-232eebd230d5"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""PauseScrollWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Arrow Keys"",
                    ""id"": ""ffcdc23d-f93a-42b5-b849-09fb5638fe25"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""PauseNavigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""348c377a-8b29-4e29-bc3b-f09b8cda9e6c"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""PauseNavigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3b2750b3-991b-49f5-8b9f-346a9db02218"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""PauseNavigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e7126ccd-5942-42dd-8980-1ea7bf0cf40c"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""PauseNavigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""78f1c9c7-f486-47a2-abbd-de88a2770171"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""PauseNavigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""WASD Keys"",
                    ""id"": ""b590b10f-1c6d-45da-9922-3fe849dce33a"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""PauseNavigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""5b443705-8184-4ecd-a535-580608d572be"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""PauseNavigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b47cf305-7094-4715-b1bd-70f1a73a8296"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""PauseNavigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""8b45cd84-f1ce-428e-9dd7-0b4aaf386c9a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""PauseNavigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""6e42e087-b445-437c-8f1f-4f6a94c867dd"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""PauseNavigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""3106d53a-b39b-40be-a458-4ef436b30b66"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""PauseNavigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Gamepad Left Stick"",
                    ""id"": ""ca9f60f7-a2dd-485c-941c-99812d3fb987"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""PauseNavigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""88091e6d-45dc-4ff8-98f5-c722346e94a6"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""PauseNavigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""fb2a9190-3daf-4a7f-841c-32e44b635b9d"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""PauseNavigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""149e0aec-b958-4971-949e-09381fa1e4ff"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""PauseNavigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""6a838509-99d7-4370-97f7-bf063e87b754"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""PauseNavigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad Right Stick"",
                    ""id"": ""cee484fb-b591-4745-8851-cdffca15d4ad"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""PauseNavigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""4a7ff440-7c66-46bd-9d46-a39f1e29f16c"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""PauseNavigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""27ceadad-13f1-4aa7-bc00-a0a654925458"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""PauseNavigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a49184dd-208e-4e16-93b2-5a2a3d28d21f"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""PauseNavigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""008e9196-8e5f-44ca-88b1-51b1ae9373df"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""PauseNavigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""10d62469-8a57-43ec-97d1-a80b7b1221e9"",
                    ""path"": ""*/{Submit}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""PauseSubmit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""253b658c-27a9-414f-9c7f-e943b6aa1dcd"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""PauseSubmit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3880ad4c-d6f5-4c87-9c17-972061a56fa6"",
                    ""path"": ""*/{Cancel}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""PauseCancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c1487fa7-663c-4cb5-af99-86c95fc4babc"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""PausePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dc9cc981-99be-44fa-bc52-78fcd4a0e7ee"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""PausePoint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00f725f3-25eb-4b81-a19b-a2276f3634cb"",
                    ""path"": ""<Touchscreen>/touch*/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""PausePoint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""562df069-6fab-41f1-b524-8e3b2605728b"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""PauseOrientation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ade553d-ff52-4787-aa9c-a82377525f73"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""PauseQuitGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MainMenuControls"",
            ""id"": ""74a33741-c196-47ef-a189-49dd24418a31"",
            ""actions"": [
                {
                    ""name"": ""MiddleClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""61cff871-e358-47b9-8976-3058e5b86294"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""LeftClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""abb09713-14a5-452e-9091-32920e23dd4f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press""
                },
                {
                    ""name"": ""RightClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""26ae9008-095a-4c62-b9a5-a1b3a845d3bf"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""ScrollWheel"",
                    ""type"": ""PassThrough"",
                    ""id"": ""81d53d67-29a9-49bc-afef-b60ace9b3c64"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Navigate"",
                    ""type"": ""PassThrough"",
                    ""id"": ""3e0cbed5-6db5-493b-8d61-676ee22293be"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""PassThrough"",
                    ""id"": ""24fbd993-1b35-40ef-a853-89cb4694e92a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""PassThrough"",
                    ""id"": ""6c725eb3-2e37-4b2a-9eae-473377ca967a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Position"",
                    ""type"": ""PassThrough"",
                    ""id"": ""e5ccb80c-1be1-476b-9152-3043b9915205"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Point"",
                    ""type"": ""Value"",
                    ""id"": ""f0203f3b-cde3-44eb-88b9-12a90e4abd81"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Orientation"",
                    ""type"": ""Value"",
                    ""id"": ""e93fa6ad-9c87-4a66-9541-c886d3905fad"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """"
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9b3a725d-628b-408a-8a5d-055c5e9b59f0"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""MiddleClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""864eb708-742c-4b16-8246-c19503570c26"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c88a2bf7-ab0f-44e7-ad22-12df08e3a456"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""ScrollWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Arrow Keys"",
                    ""id"": ""8d5731ba-d4fb-4c43-90e0-8ca1bfe2f823"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""5c81ba4d-a1fc-44f6-a78c-584ace46473c"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1bbae3b9-d803-427e-a985-4b2b470a9d00"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""3813253d-ba82-4010-ae12-dd35bad83fef"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e021a87f-b72c-4720-8bbc-50e897a7a622"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""WASD Keys"",
                    ""id"": ""9d1a9d8f-072b-4b36-a193-97ef6932ce0b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d8dddb17-2462-4f63-bf5f-e654c6ad69ee"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b38bcc05-eac9-4165-bdc0-2bfa486705b3"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d46e03f4-d264-4668-b7e4-a2db02f71af5"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""1dfbda8e-999c-482b-b6e1-98b6ca198ad8"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""bc9ab4ca-abb7-4318-a170-70ec5301829e"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Gamepad Left Stick"",
                    ""id"": ""b8608636-78c6-4987-8122-3fc29aaf77cc"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""cf5c93cb-faa0-4896-89ab-36e6a3d38c9f"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1bfb9581-e7b6-4ead-9214-d8c8b4a0b6d1"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""95d8d647-85c9-4aa6-ac15-1ddd5fe02ade"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""1c4c2399-7d1d-451c-945b-b10e2d32f7c1"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Gamepad Right Stick"",
                    ""id"": ""9e441bd1-db15-498b-ace1-8dd99c3a85e4"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""171381a4-5ffe-4662-b527-39725927c050"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""65974937-7b8b-4467-86c8-7e2ef164afb6"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d2d6b6e9-5e05-4764-bb54-ffe2dffb34c7"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""deb6bf31-3b53-4582-bcbe-7d897d3d82cb"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""d1875390-2610-4fac-97b3-295dc3a3d2ff"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""200e9124-1d55-4320-a86d-0af3e1b8c35c"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Orientation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d18269db-3e67-4e5f-aec8-25189d84273d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""LeftClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3d55bd9a-f267-4833-b9de-600ed28ae53e"",
                    ""path"": ""<Touchscreen>/touch*/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""LeftClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0502231b-79da-4847-82cb-543fe91f7b26"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""438d1f28-d054-4b67-8b22-830b85cbebf2"",
                    ""path"": ""<Touchscreen>/touch*/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e3e61628-66c7-4990-9fc1-55486a9f5949"",
                    ""path"": ""*/{Submit}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f480afb1-b7b2-485b-8aa2-8084b009f3b1"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a8b1dfa-f104-4558-917f-c7cb750d0d5f"",
                    ""path"": ""*/{Cancel}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardAndMouse"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""KeyboardAndMouse"",
            ""bindingGroup"": ""KeyboardAndMouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // CameraControls
        m_CameraControls = asset.FindActionMap("CameraControls", throwIfNotFound: true);
        m_CameraControls_ZoomIn = m_CameraControls.FindAction("Zoom In", throwIfNotFound: true);
        m_CameraControls_GameLeftClick = m_CameraControls.FindAction("GameLeftClick", throwIfNotFound: true);
        m_CameraControls_ZoomOut = m_CameraControls.FindAction("Zoom Out", throwIfNotFound: true);
        m_CameraControls_RotateLeft = m_CameraControls.FindAction("Rotate Left", throwIfNotFound: true);
        m_CameraControls_RotateRight = m_CameraControls.FindAction("Rotate Right", throwIfNotFound: true);
        m_CameraControls_Pause = m_CameraControls.FindAction("Pause", throwIfNotFound: true);
        // PauseMenuControls
        m_PauseMenuControls = asset.FindActionMap("PauseMenuControls", throwIfNotFound: true);
        m_PauseMenuControls_PauseOrientation = m_PauseMenuControls.FindAction("PauseOrientation", throwIfNotFound: true);
        m_PauseMenuControls_PausePoint = m_PauseMenuControls.FindAction("PausePoint", throwIfNotFound: true);
        m_PauseMenuControls_PausePosition = m_PauseMenuControls.FindAction("PausePosition", throwIfNotFound: true);
        m_PauseMenuControls_PauseCancel = m_PauseMenuControls.FindAction("PauseCancel", throwIfNotFound: true);
        m_PauseMenuControls_PauseSubmit = m_PauseMenuControls.FindAction("PauseSubmit", throwIfNotFound: true);
        m_PauseMenuControls_PauseNavigate = m_PauseMenuControls.FindAction("PauseNavigate", throwIfNotFound: true);
        m_PauseMenuControls_PauseScrollWheel = m_PauseMenuControls.FindAction("PauseScrollWheel", throwIfNotFound: true);
        m_PauseMenuControls_PauseRightClick = m_PauseMenuControls.FindAction("PauseRightClick", throwIfNotFound: true);
        m_PauseMenuControls_PauseLeftClick = m_PauseMenuControls.FindAction("PauseLeftClick", throwIfNotFound: true);
        m_PauseMenuControls_PauseMiddleClick = m_PauseMenuControls.FindAction("PauseMiddleClick", throwIfNotFound: true);
        m_PauseMenuControls_PauseQuitGame = m_PauseMenuControls.FindAction("PauseQuitGame", throwIfNotFound: true);
        // MainMenuControls
        m_MainMenuControls = asset.FindActionMap("MainMenuControls", throwIfNotFound: true);
        m_MainMenuControls_MiddleClick = m_MainMenuControls.FindAction("MiddleClick", throwIfNotFound: true);
        m_MainMenuControls_LeftClick = m_MainMenuControls.FindAction("LeftClick", throwIfNotFound: true);
        m_MainMenuControls_RightClick = m_MainMenuControls.FindAction("RightClick", throwIfNotFound: true);
        m_MainMenuControls_ScrollWheel = m_MainMenuControls.FindAction("ScrollWheel", throwIfNotFound: true);
        m_MainMenuControls_Navigate = m_MainMenuControls.FindAction("Navigate", throwIfNotFound: true);
        m_MainMenuControls_Submit = m_MainMenuControls.FindAction("Submit", throwIfNotFound: true);
        m_MainMenuControls_Cancel = m_MainMenuControls.FindAction("Cancel", throwIfNotFound: true);
        m_MainMenuControls_Position = m_MainMenuControls.FindAction("Position", throwIfNotFound: true);
        m_MainMenuControls_Point = m_MainMenuControls.FindAction("Point", throwIfNotFound: true);
        m_MainMenuControls_Orientation = m_MainMenuControls.FindAction("Orientation", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CameraControls
    private readonly InputActionMap m_CameraControls;
    private ICameraControlsActions m_CameraControlsActionsCallbackInterface;
    private readonly InputAction m_CameraControls_ZoomIn;
    private readonly InputAction m_CameraControls_GameLeftClick;
    private readonly InputAction m_CameraControls_ZoomOut;
    private readonly InputAction m_CameraControls_RotateLeft;
    private readonly InputAction m_CameraControls_RotateRight;
    private readonly InputAction m_CameraControls_Pause;
    public struct CameraControlsActions
    {
        private @InputActions m_Wrapper;
        public CameraControlsActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @ZoomIn => m_Wrapper.m_CameraControls_ZoomIn;
        public InputAction @GameLeftClick => m_Wrapper.m_CameraControls_GameLeftClick;
        public InputAction @ZoomOut => m_Wrapper.m_CameraControls_ZoomOut;
        public InputAction @RotateLeft => m_Wrapper.m_CameraControls_RotateLeft;
        public InputAction @RotateRight => m_Wrapper.m_CameraControls_RotateRight;
        public InputAction @Pause => m_Wrapper.m_CameraControls_Pause;
        public InputActionMap Get() { return m_Wrapper.m_CameraControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CameraControlsActions set) { return set.Get(); }
        public void SetCallbacks(ICameraControlsActions instance)
        {
            if (m_Wrapper.m_CameraControlsActionsCallbackInterface != null)
            {
                @ZoomIn.started -= m_Wrapper.m_CameraControlsActionsCallbackInterface.OnZoomIn;
                @ZoomIn.performed -= m_Wrapper.m_CameraControlsActionsCallbackInterface.OnZoomIn;
                @ZoomIn.canceled -= m_Wrapper.m_CameraControlsActionsCallbackInterface.OnZoomIn;
                @GameLeftClick.started -= m_Wrapper.m_CameraControlsActionsCallbackInterface.OnGameLeftClick;
                @GameLeftClick.performed -= m_Wrapper.m_CameraControlsActionsCallbackInterface.OnGameLeftClick;
                @GameLeftClick.canceled -= m_Wrapper.m_CameraControlsActionsCallbackInterface.OnGameLeftClick;
                @ZoomOut.started -= m_Wrapper.m_CameraControlsActionsCallbackInterface.OnZoomOut;
                @ZoomOut.performed -= m_Wrapper.m_CameraControlsActionsCallbackInterface.OnZoomOut;
                @ZoomOut.canceled -= m_Wrapper.m_CameraControlsActionsCallbackInterface.OnZoomOut;
                @RotateLeft.started -= m_Wrapper.m_CameraControlsActionsCallbackInterface.OnRotateLeft;
                @RotateLeft.performed -= m_Wrapper.m_CameraControlsActionsCallbackInterface.OnRotateLeft;
                @RotateLeft.canceled -= m_Wrapper.m_CameraControlsActionsCallbackInterface.OnRotateLeft;
                @RotateRight.started -= m_Wrapper.m_CameraControlsActionsCallbackInterface.OnRotateRight;
                @RotateRight.performed -= m_Wrapper.m_CameraControlsActionsCallbackInterface.OnRotateRight;
                @RotateRight.canceled -= m_Wrapper.m_CameraControlsActionsCallbackInterface.OnRotateRight;
                @Pause.started -= m_Wrapper.m_CameraControlsActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_CameraControlsActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_CameraControlsActionsCallbackInterface.OnPause;
            }
            m_Wrapper.m_CameraControlsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @ZoomIn.started += instance.OnZoomIn;
                @ZoomIn.performed += instance.OnZoomIn;
                @ZoomIn.canceled += instance.OnZoomIn;
                @GameLeftClick.started += instance.OnGameLeftClick;
                @GameLeftClick.performed += instance.OnGameLeftClick;
                @GameLeftClick.canceled += instance.OnGameLeftClick;
                @ZoomOut.started += instance.OnZoomOut;
                @ZoomOut.performed += instance.OnZoomOut;
                @ZoomOut.canceled += instance.OnZoomOut;
                @RotateLeft.started += instance.OnRotateLeft;
                @RotateLeft.performed += instance.OnRotateLeft;
                @RotateLeft.canceled += instance.OnRotateLeft;
                @RotateRight.started += instance.OnRotateRight;
                @RotateRight.performed += instance.OnRotateRight;
                @RotateRight.canceled += instance.OnRotateRight;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
            }
        }
    }
    public CameraControlsActions @CameraControls => new CameraControlsActions(this);

    // PauseMenuControls
    private readonly InputActionMap m_PauseMenuControls;
    private IPauseMenuControlsActions m_PauseMenuControlsActionsCallbackInterface;
    private readonly InputAction m_PauseMenuControls_PauseOrientation;
    private readonly InputAction m_PauseMenuControls_PausePoint;
    private readonly InputAction m_PauseMenuControls_PausePosition;
    private readonly InputAction m_PauseMenuControls_PauseCancel;
    private readonly InputAction m_PauseMenuControls_PauseSubmit;
    private readonly InputAction m_PauseMenuControls_PauseNavigate;
    private readonly InputAction m_PauseMenuControls_PauseScrollWheel;
    private readonly InputAction m_PauseMenuControls_PauseRightClick;
    private readonly InputAction m_PauseMenuControls_PauseLeftClick;
    private readonly InputAction m_PauseMenuControls_PauseMiddleClick;
    private readonly InputAction m_PauseMenuControls_PauseQuitGame;
    public struct PauseMenuControlsActions
    {
        private @InputActions m_Wrapper;
        public PauseMenuControlsActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @PauseOrientation => m_Wrapper.m_PauseMenuControls_PauseOrientation;
        public InputAction @PausePoint => m_Wrapper.m_PauseMenuControls_PausePoint;
        public InputAction @PausePosition => m_Wrapper.m_PauseMenuControls_PausePosition;
        public InputAction @PauseCancel => m_Wrapper.m_PauseMenuControls_PauseCancel;
        public InputAction @PauseSubmit => m_Wrapper.m_PauseMenuControls_PauseSubmit;
        public InputAction @PauseNavigate => m_Wrapper.m_PauseMenuControls_PauseNavigate;
        public InputAction @PauseScrollWheel => m_Wrapper.m_PauseMenuControls_PauseScrollWheel;
        public InputAction @PauseRightClick => m_Wrapper.m_PauseMenuControls_PauseRightClick;
        public InputAction @PauseLeftClick => m_Wrapper.m_PauseMenuControls_PauseLeftClick;
        public InputAction @PauseMiddleClick => m_Wrapper.m_PauseMenuControls_PauseMiddleClick;
        public InputAction @PauseQuitGame => m_Wrapper.m_PauseMenuControls_PauseQuitGame;
        public InputActionMap Get() { return m_Wrapper.m_PauseMenuControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PauseMenuControlsActions set) { return set.Get(); }
        public void SetCallbacks(IPauseMenuControlsActions instance)
        {
            if (m_Wrapper.m_PauseMenuControlsActionsCallbackInterface != null)
            {
                @PauseOrientation.started -= m_Wrapper.m_PauseMenuControlsActionsCallbackInterface.OnPauseOrientation;
                @PauseOrientation.performed -= m_Wrapper.m_PauseMenuControlsActionsCallbackInterface.OnPauseOrientation;
                @PauseOrientation.canceled -= m_Wrapper.m_PauseMenuControlsActionsCallbackInterface.OnPauseOrientation;
                @PausePoint.started -= m_Wrapper.m_PauseMenuControlsActionsCallbackInterface.OnPausePoint;
                @PausePoint.performed -= m_Wrapper.m_PauseMenuControlsActionsCallbackInterface.OnPausePoint;
                @PausePoint.canceled -= m_Wrapper.m_PauseMenuControlsActionsCallbackInterface.OnPausePoint;
                @PausePosition.started -= m_Wrapper.m_PauseMenuControlsActionsCallbackInterface.OnPausePosition;
                @PausePosition.performed -= m_Wrapper.m_PauseMenuControlsActionsCallbackInterface.OnPausePosition;
                @PausePosition.canceled -= m_Wrapper.m_PauseMenuControlsActionsCallbackInterface.OnPausePosition;
                @PauseCancel.started -= m_Wrapper.m_PauseMenuControlsActionsCallbackInterface.OnPauseCancel;
                @PauseCancel.performed -= m_Wrapper.m_PauseMenuControlsActionsCallbackInterface.OnPauseCancel;
                @PauseCancel.canceled -= m_Wrapper.m_PauseMenuControlsActionsCallbackInterface.OnPauseCancel;
                @PauseSubmit.started -= m_Wrapper.m_PauseMenuControlsActionsCallbackInterface.OnPauseSubmit;
                @PauseSubmit.performed -= m_Wrapper.m_PauseMenuControlsActionsCallbackInterface.OnPauseSubmit;
                @PauseSubmit.canceled -= m_Wrapper.m_PauseMenuControlsActionsCallbackInterface.OnPauseSubmit;
                @PauseNavigate.started -= m_Wrapper.m_PauseMenuControlsActionsCallbackInterface.OnPauseNavigate;
                @PauseNavigate.performed -= m_Wrapper.m_PauseMenuControlsActionsCallbackInterface.OnPauseNavigate;
                @PauseNavigate.canceled -= m_Wrapper.m_PauseMenuControlsActionsCallbackInterface.OnPauseNavigate;
                @PauseScrollWheel.started -= m_Wrapper.m_PauseMenuControlsActionsCallbackInterface.OnPauseScrollWheel;
                @PauseScrollWheel.performed -= m_Wrapper.m_PauseMenuControlsActionsCallbackInterface.OnPauseScrollWheel;
                @PauseScrollWheel.canceled -= m_Wrapper.m_PauseMenuControlsActionsCallbackInterface.OnPauseScrollWheel;
                @PauseRightClick.started -= m_Wrapper.m_PauseMenuControlsActionsCallbackInterface.OnPauseRightClick;
                @PauseRightClick.performed -= m_Wrapper.m_PauseMenuControlsActionsCallbackInterface.OnPauseRightClick;
                @PauseRightClick.canceled -= m_Wrapper.m_PauseMenuControlsActionsCallbackInterface.OnPauseRightClick;
                @PauseLeftClick.started -= m_Wrapper.m_PauseMenuControlsActionsCallbackInterface.OnPauseLeftClick;
                @PauseLeftClick.performed -= m_Wrapper.m_PauseMenuControlsActionsCallbackInterface.OnPauseLeftClick;
                @PauseLeftClick.canceled -= m_Wrapper.m_PauseMenuControlsActionsCallbackInterface.OnPauseLeftClick;
                @PauseMiddleClick.started -= m_Wrapper.m_PauseMenuControlsActionsCallbackInterface.OnPauseMiddleClick;
                @PauseMiddleClick.performed -= m_Wrapper.m_PauseMenuControlsActionsCallbackInterface.OnPauseMiddleClick;
                @PauseMiddleClick.canceled -= m_Wrapper.m_PauseMenuControlsActionsCallbackInterface.OnPauseMiddleClick;
                @PauseQuitGame.started -= m_Wrapper.m_PauseMenuControlsActionsCallbackInterface.OnPauseQuitGame;
                @PauseQuitGame.performed -= m_Wrapper.m_PauseMenuControlsActionsCallbackInterface.OnPauseQuitGame;
                @PauseQuitGame.canceled -= m_Wrapper.m_PauseMenuControlsActionsCallbackInterface.OnPauseQuitGame;
            }
            m_Wrapper.m_PauseMenuControlsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PauseOrientation.started += instance.OnPauseOrientation;
                @PauseOrientation.performed += instance.OnPauseOrientation;
                @PauseOrientation.canceled += instance.OnPauseOrientation;
                @PausePoint.started += instance.OnPausePoint;
                @PausePoint.performed += instance.OnPausePoint;
                @PausePoint.canceled += instance.OnPausePoint;
                @PausePosition.started += instance.OnPausePosition;
                @PausePosition.performed += instance.OnPausePosition;
                @PausePosition.canceled += instance.OnPausePosition;
                @PauseCancel.started += instance.OnPauseCancel;
                @PauseCancel.performed += instance.OnPauseCancel;
                @PauseCancel.canceled += instance.OnPauseCancel;
                @PauseSubmit.started += instance.OnPauseSubmit;
                @PauseSubmit.performed += instance.OnPauseSubmit;
                @PauseSubmit.canceled += instance.OnPauseSubmit;
                @PauseNavigate.started += instance.OnPauseNavigate;
                @PauseNavigate.performed += instance.OnPauseNavigate;
                @PauseNavigate.canceled += instance.OnPauseNavigate;
                @PauseScrollWheel.started += instance.OnPauseScrollWheel;
                @PauseScrollWheel.performed += instance.OnPauseScrollWheel;
                @PauseScrollWheel.canceled += instance.OnPauseScrollWheel;
                @PauseRightClick.started += instance.OnPauseRightClick;
                @PauseRightClick.performed += instance.OnPauseRightClick;
                @PauseRightClick.canceled += instance.OnPauseRightClick;
                @PauseLeftClick.started += instance.OnPauseLeftClick;
                @PauseLeftClick.performed += instance.OnPauseLeftClick;
                @PauseLeftClick.canceled += instance.OnPauseLeftClick;
                @PauseMiddleClick.started += instance.OnPauseMiddleClick;
                @PauseMiddleClick.performed += instance.OnPauseMiddleClick;
                @PauseMiddleClick.canceled += instance.OnPauseMiddleClick;
                @PauseQuitGame.started += instance.OnPauseQuitGame;
                @PauseQuitGame.performed += instance.OnPauseQuitGame;
                @PauseQuitGame.canceled += instance.OnPauseQuitGame;
            }
        }
    }
    public PauseMenuControlsActions @PauseMenuControls => new PauseMenuControlsActions(this);

    // MainMenuControls
    private readonly InputActionMap m_MainMenuControls;
    private IMainMenuControlsActions m_MainMenuControlsActionsCallbackInterface;
    private readonly InputAction m_MainMenuControls_MiddleClick;
    private readonly InputAction m_MainMenuControls_LeftClick;
    private readonly InputAction m_MainMenuControls_RightClick;
    private readonly InputAction m_MainMenuControls_ScrollWheel;
    private readonly InputAction m_MainMenuControls_Navigate;
    private readonly InputAction m_MainMenuControls_Submit;
    private readonly InputAction m_MainMenuControls_Cancel;
    private readonly InputAction m_MainMenuControls_Position;
    private readonly InputAction m_MainMenuControls_Point;
    private readonly InputAction m_MainMenuControls_Orientation;
    public struct MainMenuControlsActions
    {
        private @InputActions m_Wrapper;
        public MainMenuControlsActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @MiddleClick => m_Wrapper.m_MainMenuControls_MiddleClick;
        public InputAction @LeftClick => m_Wrapper.m_MainMenuControls_LeftClick;
        public InputAction @RightClick => m_Wrapper.m_MainMenuControls_RightClick;
        public InputAction @ScrollWheel => m_Wrapper.m_MainMenuControls_ScrollWheel;
        public InputAction @Navigate => m_Wrapper.m_MainMenuControls_Navigate;
        public InputAction @Submit => m_Wrapper.m_MainMenuControls_Submit;
        public InputAction @Cancel => m_Wrapper.m_MainMenuControls_Cancel;
        public InputAction @Position => m_Wrapper.m_MainMenuControls_Position;
        public InputAction @Point => m_Wrapper.m_MainMenuControls_Point;
        public InputAction @Orientation => m_Wrapper.m_MainMenuControls_Orientation;
        public InputActionMap Get() { return m_Wrapper.m_MainMenuControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainMenuControlsActions set) { return set.Get(); }
        public void SetCallbacks(IMainMenuControlsActions instance)
        {
            if (m_Wrapper.m_MainMenuControlsActionsCallbackInterface != null)
            {
                @MiddleClick.started -= m_Wrapper.m_MainMenuControlsActionsCallbackInterface.OnMiddleClick;
                @MiddleClick.performed -= m_Wrapper.m_MainMenuControlsActionsCallbackInterface.OnMiddleClick;
                @MiddleClick.canceled -= m_Wrapper.m_MainMenuControlsActionsCallbackInterface.OnMiddleClick;
                @LeftClick.started -= m_Wrapper.m_MainMenuControlsActionsCallbackInterface.OnLeftClick;
                @LeftClick.performed -= m_Wrapper.m_MainMenuControlsActionsCallbackInterface.OnLeftClick;
                @LeftClick.canceled -= m_Wrapper.m_MainMenuControlsActionsCallbackInterface.OnLeftClick;
                @RightClick.started -= m_Wrapper.m_MainMenuControlsActionsCallbackInterface.OnRightClick;
                @RightClick.performed -= m_Wrapper.m_MainMenuControlsActionsCallbackInterface.OnRightClick;
                @RightClick.canceled -= m_Wrapper.m_MainMenuControlsActionsCallbackInterface.OnRightClick;
                @ScrollWheel.started -= m_Wrapper.m_MainMenuControlsActionsCallbackInterface.OnScrollWheel;
                @ScrollWheel.performed -= m_Wrapper.m_MainMenuControlsActionsCallbackInterface.OnScrollWheel;
                @ScrollWheel.canceled -= m_Wrapper.m_MainMenuControlsActionsCallbackInterface.OnScrollWheel;
                @Navigate.started -= m_Wrapper.m_MainMenuControlsActionsCallbackInterface.OnNavigate;
                @Navigate.performed -= m_Wrapper.m_MainMenuControlsActionsCallbackInterface.OnNavigate;
                @Navigate.canceled -= m_Wrapper.m_MainMenuControlsActionsCallbackInterface.OnNavigate;
                @Submit.started -= m_Wrapper.m_MainMenuControlsActionsCallbackInterface.OnSubmit;
                @Submit.performed -= m_Wrapper.m_MainMenuControlsActionsCallbackInterface.OnSubmit;
                @Submit.canceled -= m_Wrapper.m_MainMenuControlsActionsCallbackInterface.OnSubmit;
                @Cancel.started -= m_Wrapper.m_MainMenuControlsActionsCallbackInterface.OnCancel;
                @Cancel.performed -= m_Wrapper.m_MainMenuControlsActionsCallbackInterface.OnCancel;
                @Cancel.canceled -= m_Wrapper.m_MainMenuControlsActionsCallbackInterface.OnCancel;
                @Position.started -= m_Wrapper.m_MainMenuControlsActionsCallbackInterface.OnPosition;
                @Position.performed -= m_Wrapper.m_MainMenuControlsActionsCallbackInterface.OnPosition;
                @Position.canceled -= m_Wrapper.m_MainMenuControlsActionsCallbackInterface.OnPosition;
                @Point.started -= m_Wrapper.m_MainMenuControlsActionsCallbackInterface.OnPoint;
                @Point.performed -= m_Wrapper.m_MainMenuControlsActionsCallbackInterface.OnPoint;
                @Point.canceled -= m_Wrapper.m_MainMenuControlsActionsCallbackInterface.OnPoint;
                @Orientation.started -= m_Wrapper.m_MainMenuControlsActionsCallbackInterface.OnOrientation;
                @Orientation.performed -= m_Wrapper.m_MainMenuControlsActionsCallbackInterface.OnOrientation;
                @Orientation.canceled -= m_Wrapper.m_MainMenuControlsActionsCallbackInterface.OnOrientation;
            }
            m_Wrapper.m_MainMenuControlsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MiddleClick.started += instance.OnMiddleClick;
                @MiddleClick.performed += instance.OnMiddleClick;
                @MiddleClick.canceled += instance.OnMiddleClick;
                @LeftClick.started += instance.OnLeftClick;
                @LeftClick.performed += instance.OnLeftClick;
                @LeftClick.canceled += instance.OnLeftClick;
                @RightClick.started += instance.OnRightClick;
                @RightClick.performed += instance.OnRightClick;
                @RightClick.canceled += instance.OnRightClick;
                @ScrollWheel.started += instance.OnScrollWheel;
                @ScrollWheel.performed += instance.OnScrollWheel;
                @ScrollWheel.canceled += instance.OnScrollWheel;
                @Navigate.started += instance.OnNavigate;
                @Navigate.performed += instance.OnNavigate;
                @Navigate.canceled += instance.OnNavigate;
                @Submit.started += instance.OnSubmit;
                @Submit.performed += instance.OnSubmit;
                @Submit.canceled += instance.OnSubmit;
                @Cancel.started += instance.OnCancel;
                @Cancel.performed += instance.OnCancel;
                @Cancel.canceled += instance.OnCancel;
                @Position.started += instance.OnPosition;
                @Position.performed += instance.OnPosition;
                @Position.canceled += instance.OnPosition;
                @Point.started += instance.OnPoint;
                @Point.performed += instance.OnPoint;
                @Point.canceled += instance.OnPoint;
                @Orientation.started += instance.OnOrientation;
                @Orientation.performed += instance.OnOrientation;
                @Orientation.canceled += instance.OnOrientation;
            }
        }
    }
    public MainMenuControlsActions @MainMenuControls => new MainMenuControlsActions(this);
    private int m_KeyboardAndMouseSchemeIndex = -1;
    public InputControlScheme KeyboardAndMouseScheme
    {
        get
        {
            if (m_KeyboardAndMouseSchemeIndex == -1) m_KeyboardAndMouseSchemeIndex = asset.FindControlSchemeIndex("KeyboardAndMouse");
            return asset.controlSchemes[m_KeyboardAndMouseSchemeIndex];
        }
    }
    public interface ICameraControlsActions
    {
        void OnZoomIn(InputAction.CallbackContext context);
        void OnGameLeftClick(InputAction.CallbackContext context);
        void OnZoomOut(InputAction.CallbackContext context);
        void OnRotateLeft(InputAction.CallbackContext context);
        void OnRotateRight(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
    }
    public interface IPauseMenuControlsActions
    {
        void OnPauseOrientation(InputAction.CallbackContext context);
        void OnPausePoint(InputAction.CallbackContext context);
        void OnPausePosition(InputAction.CallbackContext context);
        void OnPauseCancel(InputAction.CallbackContext context);
        void OnPauseSubmit(InputAction.CallbackContext context);
        void OnPauseNavigate(InputAction.CallbackContext context);
        void OnPauseScrollWheel(InputAction.CallbackContext context);
        void OnPauseRightClick(InputAction.CallbackContext context);
        void OnPauseLeftClick(InputAction.CallbackContext context);
        void OnPauseMiddleClick(InputAction.CallbackContext context);
        void OnPauseQuitGame(InputAction.CallbackContext context);
    }
    public interface IMainMenuControlsActions
    {
        void OnMiddleClick(InputAction.CallbackContext context);
        void OnLeftClick(InputAction.CallbackContext context);
        void OnRightClick(InputAction.CallbackContext context);
        void OnScrollWheel(InputAction.CallbackContext context);
        void OnNavigate(InputAction.CallbackContext context);
        void OnSubmit(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnPosition(InputAction.CallbackContext context);
        void OnPoint(InputAction.CallbackContext context);
        void OnOrientation(InputAction.CallbackContext context);
    }
}
